apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secret
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
